install:
	pip2 install --no-cache-dir --user -U duckietown-shell


# Before being able to submit, you need to run:
# dts tok set YOUR_TOKEN
# dts challenges config --docker-username MY_DOCKER_USERNAME


submit:
	dts challenges submit
